from typing import Protocol

from ai_framework.entities.session import Session


class ISessionStore(Protocol):
    def get_or_create(self, thread_id: str) -> Session: ...
    def get(self, thread_id: str) -> Session | None: ...
    def update_language(self, thread_id: str, language: str) -> None: ...
    def touch(self, thread_id: str) -> None: ...
